### ISSUE TITLE
Sign In (repeat) error

### ISSUE THREAD

**Issue by Avatarchik** [Thaina/google-signin-unity#5]
2024.03.21 23:00:07.230 28533 28569 Error SignInFragment Request not configured! Failing authenticate
2024.03.21 23:00:07.234 28533 28569 Error Unity AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.googlesignin.IListener com.google.googlesignin.TokenRequest.getHandle()' on a null object reference
2024.03.21 23:00:07.234 28533 28569 Error Unity java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.googlesignin.IListener com.google.googlesignin.TokenRequest.getHandle()' on a null object reference
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at com.google.googlesignin.GoogleSignInHelper.signIn(GoogleSignInHelper.java:101)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at android.os.Looper.loopOnce(Looper.java:226)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at android.os.Looper.loop(Looper.java:313)
2024.03.21 23:00:07.234 28533 28569 Error Unity 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
2024.03.21 23:00:07.234 28533 28569 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
2024.03.21 23:00:07.234 28533 28569 Error Unity   at UnityEngine.AndroidJNISafe.CallStaticO

If you log in and then log out and try to log in again, it gives an error

Sign In -> Sign Out ->Sign In - error

**Comment by Avatarchik** [comment]
I did it this way in the GoogleSignInFragment.java file
in the ClearRequest function
commented out
//request = null;

`private synchronized void clearRequest(boolean cancel) {
    if (cancel && request != null) {
      // Cancel request.
      request.cancel();
    }
    //request = null;
    setState(getActivity() != null ? State.READY : State.NEW);
  }`
